"""add saran table

Revision ID: fd18768fdcec
Revises: 2a5e7bf7b8b4
Create Date: 2026-08-15 01:04:23.823023

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fd18768fdcec'
down_revision = '2a5e7bf7b8b4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('saran',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('nama', sa.String(length=100), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=False),
    sa.Column('pesan', sa.Text(), nullable=False),
    sa.Column('sudah_dibaca', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('saran', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_saran_sudah_dibaca'), ['sudah_dibaca'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('saran', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_saran_sudah_dibaca'))

    op.drop_table('saran')
    # ### end Alembic commands ###
